version: '3.8'

services:
  tux-server:
    image: ghcr.io/devendev-team/tux-server:latest
    build: .
    container_name: tux-sync-server
    ports:
      - "8282:8282"
    environment:
      # Mot de passe d'accès au panneau d'administration (/admin)
      - ADMIN_PASSWORD=mon_mot_de_passe_admin_1234
    volumes:
      # Persister le dossier de données contenant les JSON des utilisateurs
      - ./data:/app/data
      # Monter la PWA mobile pour qu'elle soit servie à la racine
      - ./tux-mobile:/app/tux-mobile
    restart: unless-stopped
